name: Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.2', '3.3', '3.4']

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}

    env:
      POLYPHONY_LIBEV: "1"

    steps:
    - name: Setup machine
      uses: actions/checkout@v1
    - name: Setup Ruby and install deps
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
        cache-version: 4
    - name: Run tests
      run:  bundle exec rake test
