name: Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        ruby: ['2.7', '3.0', 'head']

    name: >-
      ${{matrix.os}}, ${{matrix.ruby}}

    runs-on: ${{matrix.os}}

    env:
      POLYPHONY_USE_LIBEV: "1"

    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true # 'bundle install' and cache
        
    # - name: Install dependencies
    #   run: |
    #     gem install bundler
    #     POLYPHONY_USE_LIBEV=1 bundle install
    - name: Run tests
      run:  bundle exec rake test
